services:
  - type: web
    name: emtrixz-technology
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_DEBUG
        value: "false"
      - key: MAILERSEND_API_KEY
        sync: false
      - key: MAILERSEND_FROM_EMAIL
        sync: false